// <auto-generated />
using System;
using LoLPA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoLPA.Database.Migrations
{
    [DbContext(typeof(MatchProcessorContext))]
    partial class MatchProcessorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoLPA.Database.Models.MatchProcessor.ProcessError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ErrorDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessError");
                });

            modelBuilder.Entity("LoLPA.Database.Models.MatchProcessor.ProcessorQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessErrorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessErrorId");

                    b.ToTable("ProcessorQueue");
                });

            modelBuilder.Entity("LoLPA.Database.Models.MatchProcessor.ProcessorQueueItem", b =>
                {
                    b.HasOne("LoLPA.Database.Models.MatchProcessor.ProcessError", "ProcessError")
                        .WithMany()
                        .HasForeignKey("ProcessErrorId");

                    b.Navigation("ProcessError");
                });
#pragma warning restore 612, 618
        }
    }
}
